### ISSUE TITLE
Basic website organization

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/gensc.github.io#1]
Organization of the new GSC website was sketched out at the CIG hackathon in the spring, and documented at https://docs.google.com/document/d/15HwpHeNfPXNZH8Caz8bm4X3SbkCirBAUF6Jut8paEXE/edit. 

I am hoping that someone who help make those drawings (@lschriml @only1chunts) can translate that into some simple text in the comments below.

**Comment by lschriml** [comment]
Found Notes from website review: 
[Gensc.org google doc ](https://docs.google.com/spreadsheets/d/1-NnKtSJAs6Tj54QTI0SvT71fLiBY_47HDB5JjlxxqDo/edit#gid=0)

**Comment by ramonawalls** [comment]
Status: All of this except the calendar seems to be in place.

**Comment by ramonawalls** [comment]
I added the calendar (yay), but the menu or page needs to be wider so it does not wrap onto the next line.

**Comment by only1chunts** [comment]
I think we can happily put the calendar link under the "meetings" heading.
Done.

**Comment by ramonawalls** [comment]
I made it its own tab, but it doesn't fit right, so I will move it to
meetings.

>

**Comment by only1chunts** [comment]
I already moved it :-D
