### ISSUE TITLE
 create GSC18 meeting page

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/gensc.github.io#16]
**Aim**
To create the GSC18 page in the new website

The meeting age is currently listed on the GSC website as http://wiki.gensc.org/index.php?title=GSC_18 **BUT** that is a link to the old old wiki that no longer working properly so will need some investigation to find it!
@lschriml may have a copy somewhere of this page in the GSC google drive, there is a doc that has some text copied from the old wiki (https://docs.google.com/document/d/15QVFRh-LjrpOrRBROEWw7r-Lv3FdSnxk-rpkuftYclU/edit) but that doesn't appear to include GSC18.

An alternative might be to look in the [Wayback machine](https://web.archive.org/web/20190103095703/http://wiki.gensc.org/index.php?title=GSC_18)

When its been found, the content of that needs converting to MD and uploading to this GitHub repo as "GSC18.md" here: https://github.com/GenomicsStandardsConsortium/gensc.github.io/tree/master/pages/meetings

`For guide on creating markdown files from html see `[readme.md](https://github.com/GenomicsStandardsConsortium/gensc.github.io/blob/master/README.md)

Any images used need to be saved here https://github.com/GenomicsStandardsConsortium/gensc.github.io/tree/master/images/
NB- sponsors images may already exist if used in other pages already.

Any additional files e.g. PDF version of agenda or schedule, powerpoint slides etc. need to be saved here:
https://github.com/GenomicsStandardsConsortium/gensc.github.io/tree/master/other-media/
NB- Be aware of the need for unique file names here, e.g. "agenda.pdf" is not likely to be unique! consider adding prefix of "gsc20-meeting" to all files to be associated with this meeting page.

**Extra content**
Where possible any augmentation of the page with media files from currently unlinked sources (e.g. youtube, images, slideshows etc) is strongly encouraged.

**Comment by only1chunts** [comment]
main page has been imported, see https://www.gensc.org/pages/meetings/GSC18/GSC18.html
However, we're missing the Agenda Doc, and the Island Sampling Day document.
@lynn are you able to find those documents, (either PDF or google doc files) If so, I can add them to the repo so they are linked from the meeting page.

**Comment by mslarae13** [comment]
@only1chunts I think we can close this? :)

**Comment by lschriml** [comment]
Yes, please close this one Montana :)On Aug 30, 2024, at 2:13 PM, Montana ***@***.***> wrote:﻿
@only1chunts I think we can close this? :)
