### ISSUE TITLE
Moving default from 'master' to 'main' 

### ISSUE THREAD

**Issue by lschriml** [GenomicsStandardsConsortium/gensc.github.io#45]
For each of the GSC GitHub repositories, to change from master to main as the 

 

Steps:
(1)   in your local repository, while on the master branch 
>  git branch -m master main
>  git push -u origin main 

(2) Update Repo

in GitHub: 
Navigate to your repository > Settings > Branches
  - select 'main' as your default branch 

If you want to remove the 'master'
  Navigate to Code > Branches and delete master

https://dev.to/afrodevgirl/replacing-master-with-main-in-github-2fjf

**Comment by only1chunts** [comment]
done- default branch is now named main instead of master
