### ISSUE TITLE
update GSC-members page

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/gensc.github.io#50]
The community or GSC-Members page contains a list of names and affiliations of people.
https://genomicsstandardsconsortium.github.io/gensc.github.io/pages/about/GSC-members.html
This is list is always going to be out of date, so I think it needs to be removed, instead is there a way to insert the google-group list of members in a dynamic way? i.e. the list of current GSC members is the same as the mailing list (if you're not on the mailing list you cannot be considered a current! member as you will have way to know whats going on in the GSC.
Alternatively, we might consider using GitHub members as a way to attribute GSC membership? This has the issue that it requires all GSC members to have and use GitHub accounts. 
Either way, we need this GSC community members page to show HOW to become an active member and how to discover who is already a member.
Ideas please....

**Comment by ramonawalls** [comment]
I agree that having a page called Community makes more sense than a Members page. Building off @only1chunts suggestions for content, I will draft a straw man page.

**Comment by lschriml** [comment]
Agreed !!

**Comment by only1chunts** [comment]
I just made a minor update to the community page to change Projects using GSC to be adopters, only because we have GSC projects so i didn't want to get the two different things confused.
Also I just noticed that the (compliance page)[ https://genomicsstandardsconsortium.github.io/gensc.github.io/pages/standards/compliance.html] actually already has a section on adopters so we need to think about where the best place for this is and not duplicate the section in two places.

**Comment by only1chunts** [comment]
This has been updated and a [join-us](https://www.gensc.org/pages/membership.html) page has been added to tell people how to get involved, so closing this ticket
