### ISSUE TITLE
Add status column to GSC projects page

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/gensc.github.io#51]
The Project page has a table with all the projects that has a column for date. I think this column should be relabeled "Start date". Then we should add another column for "Status". 

Statuses could be: Started, Ongoing, Completed. 

@lschriml and @only1chunts, does this sound reasonable? Can you think of any other statuses?

**Comment by only1chunts** [comment]
the idea is reasonable, but the changes make the table look oddly wide. Is there a way to keep the pages all the same width? or maybe we need to somehow adjust the "Dinky theme" page layout to make all pages wider?

I'm not sure a project is ever "completed" is it? Maybe for any that are finished, we just have a separate table for those?

**Comment by lschriml** [comment]
Looks good to me.
Cheers,
Lynn

**Comment by only1chunts** [comment]
column has been added so closing this ticket.
We may need to create a new ticket to get the status column values updated!
