### ISSUE TITLE
Rethink project pages

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/gensc.github.io#52]
The project pages have been copied over from the old website. The content is what was originally included in the project proposal, but this doesn't provide much information on what the project do or did. Although this is interesting for project history and could be stored somewhere (maybe in our Google drive or in a wiki), it is not terribly useful for anyone coming to the site now.

I propose a new layout for the pages:

# Project Title

**Comment by lschriml** [comment]
Sounds good to me.
Cheers,
Lynn

**Comment by scotttighe** [comment]
Agreed

Scott

**Comment by lschriml** [comment]
[GSC Project Proposal Template.docx](https://github.com/GenomicsStandardsConsortium/gensc.github.io/files/11498656/GSC.Project.Proposal.Template.docx)

@only1chunts -- Chris, can you please add this template to the GSC website, Project page?

This file is saved in the GSC dropbox, projects folder.

Cheers,
Lynn

**Comment by only1chunts** [comment]
This was discussed at the GSC board meeting in June 2023. The recomendations were:

- Separate lists/tables for active projects and former/inactive projects
- Should include links and contact information wherever possible
- Separate internal and external projects, i.e. remove "mixs" and packages
- New project should be reviewed quarterly by the board at quarterly meetings.
- Review full projects list every year at annual meeting to retire old ones.

**Comment by only1chunts** [comment]
The checklist of things to be done has been done with the following notes:
"mixs" extensions have not all been removed as some are still collaborative projects so linking to the partners is useful
Reviewing of new and existing projects will be done, and was discussed at the last board meeting, but there is no mention of that added to the gensc.org website.
