### ISSUE TITLE
Update standards intro page to include MIUViG

### ISSUE THREAD

**Issue by emileyfadrosh** [GenomicsStandardsConsortium/gensc.github.io#58]
Thanks @only1chunts for the work on the website. If you could please update the [standards intro page](https://genomicsstandardsconsortium.github.io/gensc.github.io/pages/standards-intro.html) to include the MIUViG standards, that would be great: 

MIUViG: Minimum Information about an Uncultivated Virus Genome, see publication https://pubmed.ncbi.nlm.nih.gov/30556814/

**Comment by only1chunts** [comment]
@emileyfadrosh great spot, thank you. I've updated the page now, please reopen this ticket if there are still things that need correcting.
