### ISSUE TITLE
URL w3id links - not working?

### ISSUE THREAD

**Issue by maxmaronna** [GenomicsStandardsConsortium/gensc.github.io#63]
The URL w3id links are not working.

Example: 
http://www.gensc.org/pages/standards/search-terms.html? (I tried to open the link for MIXS:0000029)
MIXS:0000029
Term name: specific host
URL: https://w3id.org/gensc/terms/MIXS_0000029

Web page answer:
"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at support@w3id.org to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log."

Cheers
max maronna

**Comment by only1chunts** [comment]
Hi, Many thanks for noticing this. We have had some issues with getting the w3id to work, so as a temporary fix I have updated the URL links to point to the relevant url instead. Hopefully, now that should be useable for you whilst we work on making the W3IDs resolve properly.
Thanks.

**Comment by maxmaronna** [comment]
Happy to help :)
By the way, do you have a spreadsheet combining "MIxS at NCBI" and "MIxS_at_DwC"? I didn´t find a easy way to cross-reference harmonizations-equivalencies amon them...I did an approach taking into account MIxS v5.0 here https://docs.google.com/spreadsheets/d/1O8UZ5Myqylpdpk94G_zo2r0LN1hwWvOzRQ0SHDDsQEM/edit?usp=sharing
Cheers,
max
