### ISSUE TITLE
add guide to acronym pronunciation

### ISSUE THREAD

**Issue by sformel-usgs** [GenomicsStandardsConsortium/gensc.github.io#65]
**Is your feature request related to a problem? Please describe.**
It's unclear how the standards MIMARKS and MIxS should be pronounced when said out loud.

**Describe the solution you'd like**
Add information to the website with a phonetic pronunciation of how it is most often said by the creators/maintainers.

**Describe alternatives you've considered**
Point to a paper or another place where this is already published. I did some searching but couldn't find it anywhere.

**Additional context**
While MIGS and MIMS seem to be pretty straightforward, for MIMARKS, I've heard MY-MARKS and MEE-MARKS.  For MIxS, I've heard Mix, Mixes, and My-sees.  I realize this is kind of a superficial concern, but it would be simple way to remove a small stumbling block and help novices feel confident and comfortable asking questions about the standard.

**Comment by only1chunts** [comment]
Hi, thanks for raising this. I dont think we're particularly fussy about how its pronounced but you are correct that it would be good to provide some guidance. I will add it to the draft manuscript we are putting together as a point to cover. 
For me personally, I say "Mix-es", but use "My" as prefix for the individual checklists, e.g. My-Marks

**Comment by sformel-usgs** [comment]
That sounds reasonable. Thanks for taking the time to consider it!

**Comment by only1chunts** [comment]
added the pheonetic "MIX-ess" pronunciation to the [standards-intro](https://www.gensc.org/pages/standards-intro.html) page.
