### ISSUE TITLE
Sending a message to the gensc-cig googlegroups did not work 

### ISSUE THREAD

**Issue by ArielKomen** [GenomicsStandardsConsortium/gensc.github.io#67]
**Describe the bug**
I wanted to ask a general question to the Genomic Standards Consortium. I found the e-mail address gensc-cig@googlegroups.com on http://www.gensc.org/pages/contact.html and tried to send an e-mail. However, I received an message from the mailer-daemon@googlemail.com that the googlegroups doesn't exist (which is not the case) or that I have to be part of the googlegroups to write messages. 

**Expected behavior**
Anyone should be able to send an e-mail to the e-mail adress gensc-cig@googlegroups.com if they have a general question.

**Comment by only1chunts** [comment]
@ArielKomen Many thanks for pointing this out. You are correct the group did have the settings set to only group members could post! I have no updated that, so it should now be possible to send a message via the contact us page as expected.
