### ISSUE TITLE
broken link to implementation page

### ISSUE THREAD

**Issue by sformel-usgs** [GenomicsStandardsConsortium/gensc.github.io#68]
Looks like the implementation page was renamed with a capital "I", so it broke the link from the dropdown menu.  Either the dropdown menu link should be updated to `https://www.gensc.org/pages/standards/Implementation.html` or the file in the repo should be renamed to `...pages/standards/implementation.md`

**Comment by only1chunts** [comment]
Thanks for spotting that! I'll get it fixed ASAP.

**Comment by only1chunts** [comment]
The content of the implementation.md file was already incorporated into the extensions page, so I've just removed the "Implementation" link from the Nav bar!
Perhaps in the future we may add different documentation about other ways to implement MIxS checklists in various databases/repositories/projects, which would mean the implementation page would be appropriate to add back in.  But thats content I dont have at this moment.
